/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CsNXbusVSTz
 */


export function Component() {
  return (
    <div className="bg-white dark:bg-gray-800 text-gray-800 dark:text-gray-200 p-6 rounded-lg shadow-lg">
      <h1 className="text-4xl font-bold mb-4">Portfolio</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div>
          <h2 className="text-2xl font-semibold mb-2">Personal Information</h2>
          <p>Name: Francesc</p>
          <p>Surnames: Fors Ferrer</p>
          <p>Date of Birth: November 21, 1975</p>
          <p>Place of Birth: Barcelona</p>
          <p>Current Address: C/ Rector Coch 1 </p> <p>Lloret de Mar - Girona</p>
          <p>DNI: 44004300X</p>
          <p>Mobile: +34 618900003</p>
          <p>Email: cescofors75@gmail.com</p>
          <p>Github: https://github.com/cescofors75</p>
          <p>Portfolio: www.cesco.dev</p>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-2">Education</h2>
          <div>
            <h3 className="font-medium">1997-2002: Universidad de Girona UDG</h3>
            <p>Degree: Ingeniería Técnica en Informática de Gestión</p>
          </div>
          <div>
            <h3 className="font-medium">1991-1996: Escola Núria Perpinyà Barcelona</h3>
            <p>Degree: Formación Profesional I-II, Técnico Especialista en Informática de Gestión</p>
          </div>
        </div>
      </div>
      <br/>
      <div>
          <h2 className="text-2xl font-semibold mb-2">Current Project</h2>
          <h3 className="font-medium">Baco AI</h3>
          <p>
            Description: Gives life to your own Virtual Sommelier. A service where establishments can create and manage
            their personalized sommelier with ease and speed. Link to the project: https://baco.cat/
          </p>
        </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Languages</h2>
        <p>Catalán: Native. Level C.</p>
        <p>Spanish: Native.</p>
        <p>French: Written and spoken correctly. Intermediate level.</p>
      </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Programming Languages</h2>
        <p>
          ASM, Cobol, Visual Basic,   Visual C, HTML, CSS, C++, ASP, JSP, PHP, SQL, .NET,
          XSL, XML, DRUPAL, Javascript, Ajax, React, Next.js
        </p>
      </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Operating Systems</h2>
        <p>Windows, Macintosh, Linux, IOT</p>
      </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Database Management Systems</h2>
        <p>Oracle, Mysql, SQLServer, PostgreSQL, Supabase</p>
      </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Others</h2>
        <p>Google analytics, Business Intelligence and Big Data</p>
      </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Experience</h2>
        <div>
          <h3 className="font-medium">2021-2022: Euro4x4parts</h3>
          <p>Developing computer applications for the R&D department.</p>
        </div>
        <div>
          <h3 className="font-medium">2019-2021: Euro4x4parts</h3>
          <p>Head of Accessories Department.</p>
        </div>
        <div>
          <h3 className="font-medium">2015-2019: Euro4x4parts</h3>
          <p>Director of the branch in Canarias.</p>
        </div>
        <div>
          <h3 className="font-medium">2012-2014: Euro4x4parts</h3>
          <p>Commercial technician.</p>
        </div>
        <div>
          <h3 className="font-medium">2010-2012: Euro4x4parts</h3>
          <p>Head of IT Department.</p>
        </div>
        <div>
          <h3 className="font-medium">2010-2012: HOTEL SAN CARLOS - ROSES</h3>
          <p>
            Management and maintenance of computer software and hardware at the hotel in Roses and offices in Lloret de
            Mar.
          </p>
        </div>
        <div>
          <h3 className="font-medium">2010-2012: Freelance</h3>
          <p>Website design and development: https://www.raidcostabrava.com/ - DRUPAL</p>
          <p>Website design and development: https://www.costabravareggaefest.com/ - DRUPAL</p>
          <p>Website design and development: http://www.radialtours.com/ - DRUPAL</p>
          <p>Website design and development: https://www.casarusa.cat/ - DRUPAL</p>
          <p>Website design and development: https://www.restaurantemasbusca.com/ - DRUPAL</p>
        </div>
        <div>
          <h3 className="font-medium">2007-2009: FOOTBALL AND MUSIC</h3>
          <p>
            Design of banners and stamps publicitarios. Webs of reference: www.sportsemotions.com,
            www.football-and-music.com, www.barcelona-football-tickets.com
          </p>
        </div>
        <div>
          <h3 className="font-medium">2005: MAPICASSA</h3>
          <p>
            Responsible for the IT department. Management and computer maintenance of 5 offices, Intranet, Corporate
            Web, Closed security camera circuits.
          </p>
        </div>
        <div>
          <h3 className="font-medium">2002: Freelance</h3>
          <p>Website design and development: to2djs.net - HTML, FLASH</p>
        </div>
        <div>
          <h3 className="font-medium">
            {`2001: GGG Grup Gra\u{300}fics Girona (Dpto. UdG) – Programador Durante 12 meses`}
          </h3>
        </div>
        <div>
          <h3 className="font-medium">{`2001: Disen\u{303}o y Desarrollo web ScratchComando.com - HTML, FLASH`}</h3>
        </div>
        <div>
          <h3 className="font-medium">
            {`1999: Juzgado de 1a Instancia e Instruccio\u{301}n nu\u{301}mero 6 Auxiliar Interino - Durante 12 meses`}
          </h3>
        </div>
        <div>
          <h3 className="font-medium">1994-1996: Rank Xerox Barcelona</h3>
          <p>Programador durante 14 meses.</p>
        </div>
      </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Skills</h2>
        <p>Habilidades comerciales.</p>
        <p>Capacidad organizativa y resolutiva.</p>
        <p>{`Trabajo en equipo o auto\u{301}noma.`}</p>
      </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Licenses</h2>
        <p>Carnet B1.</p>
      </div>
    </div>
  )
}
