/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CsNXbusVSTz
 */
import Link from 'next/link'

export function Component() {
  return (
    <div className="bg-white dark:bg-gray-800 text-gray-800 dark:text-gray-200 p-6 rounded-lg shadow-lg">
      <h1 className="text-4xl font-bold mb-4">Portfoli</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div>
          <h2 className="text-2xl font-semibold mb-2">Informació Personal</h2>
          <p>Nom: Francesc</p>
          <p>Cognoms: Fors Ferrer</p>
          <p>Data de Naixement: 21 de novembre de 1975</p>
          <p>Lloc de Naixement: Barcelona</p>
          <p>Adreça Actual: C/ Rector Coch 1 </p> <p>Lloret de Mar - Girona</p>
          <p>DNI: 44004300X</p>
          <p>Mòbil: +34 618900003</p>
          <p>Correu Electrònic: cescofors75@gmail.com</p>
          <Link href="https://www.linkedin.com/in/cescofors/" target="_blank">
            <p>LinkedIn: https://www.linkedin.com/in/cescofors/</p>
          </Link>
          <Link href="https://github.com/cescofors75" target="_blank">
            <p>Github: https://github.com/cescofors75</p>
          </Link>
          <Link href="https://cesco.dev">
            <p>Portfoli: www.cesco.dev</p>
          </Link>
        </div>
        <div>
          <h2 className="text-2xl font-semibold mb-2">Educació</h2>
          <div>
            <h3 className="font-medium">1997-2002: Universitat de Girona UDG</h3>
            <p>Grau: Enginyeria Tècnica en Informàtica de Gestió</p>
          </div>
          <div>
            <h3 className="font-medium">1991-1996: Escola Núria Perpinyà Barcelona</h3>
            <p>Grau: Formació Professional I-II, Tècnic Especialista en Informàtica de Gestió</p>
          </div>
        </div>
      </div>
      <br/>
      <div>
          <h2 className="text-2xl font-semibold mb-2">Projecte Actual</h2>
          <h3 className="font-medium">Baco AI</h3>
          <p>
            Descripció: Dona vida al teu propi Sommelier Virtual. Un servei on els establiments poden crear i gestionar el seu sommelier personalitzat amb facilitat i rapidesa. <Link href="https://baco.cat/" target="_blank">https://baco.cat/</Link>
          
          </p>
         <p>Acceleradora: ISDI (Escola de negocis) Barcelona (Next Generator)</p>
         <p>Microsoft Startup Founders Hub (Patrocinador)</p>
         <p>Desenvolupament de patrons de Relacions Embeddings (vectors) RAG (Retrieve and Generate) per a la generació de respostes.</p>



        </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Llengües</h2>
        <p>Català: Natiu. Nivell C.</p>
        <p>Espanyol: Natiu.</p>
        <p>Francès: Escrit i parlat correctament. Nivell intermedi.</p>
      </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Llenguatges de Programació</h2>
        <p>
          ASM, Cobol, Visual Basic, Visual C, HTML, CSS, C++, ASP, JSP, PHP, SQL, .NET, XSL, XML, DRUPAL, Javascript, Ajax, React, Next.js
        </p>
      </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Sistemes de Gestió de Bases de Dades</h2>
        <p>Oracle, Mysql, SQLServer, PostgreSQL, Supabase</p>
      </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Eines de Programació</h2>
        <p>VS-CODE, Node.js, Bun</p>
      </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">API S & Serveis</h2>
        <p>OpenAI, Stability.ai, Vercel, Mistral, Cohere</p>
      </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Sistemes Operatius</h2>
        <p>Windows, Macintosh, Linux, IOT</p>
      </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Altres</h2>
        <p>Google Analytics, Business Intelligence i Big Data, PowerBI, Azure</p>
      </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Experiència</h2>
        <div>
          <h3 className="font-medium">2021-2022: Euro4x4parts (França)</h3>
          <p>Desenvolupament d`aplicacions informàtiques per al departament de R+D. Solució OBD2. Sistema per a cotxes antics connectats a internet.</p>
        </div>
        <div>
          <h3 className="font-medium">2019-2021: Euro4x4parts (França)</h3>
          <p>Cap del Departament d`Accessoris.</p>
        </div>
        <div>
          <h3 className="font-medium">2015-2019: Euro4x4parts</h3>
          <p>Director de la sucursal a Canàries.</p>
        </div>
        <div>
          <h3 className="font-medium">2012-2014: Euro4x4parts</h3>
          <p>Tècnic comercial.</p>
        </div>
        <div>
          <h3 className="font-medium">2010-2012: Euro4x4parts</h3>
          <p>Head of IT Department.</p>
        </div>
        <div>
          <h3 className="font-medium">2010-2012: HOTEL SAN CARLOS - ROSES</h3>
          <p>
            Management and maintenance of computer software and hardware at the hotel in Roses and offices in Lloret de
            Mar.
          </p>
        </div>
        <div>
          <h3 className="font-medium">2010-2012: Freelance</h3>
          <p>Disseny i desenvolupament web: https://www.raidcostabrava.com/ - DRUPAL</p>
          <p>Disseny i desenvolupament web: https://www.costabravareggaefest.com/ - DRUPAL</p>
          <p>Disseny i desenvolupament web: http://www.radialtours.com/ - DRUPAL</p>
          <p>Disseny i desenvolupament web: https://www.casarusa.cat/ - DRUPAL</p>
          <p>Disseny i desenvolupament web: https://www.restaurantemasbusca.com/ - DRUPAL</p>
        </div>
        <div>
          <h3 className="font-medium">2007-2009: FOOTBALL AND MUSIC</h3>
          <p>Disseny de banners i segells publicitaris. Webs de referència: www.sportsemotions.com, www.football-and-music.com, www.barcelona-football-tickets.com</p>
        </div>
        <div>
          <h3 className="font-medium">2005: MAPICASSA (Tecnocasa)</h3>
          <p>Responsable del departament de TI. Gestió i manteniment informàtic de 5 oficines, Intranet, Web Corporativa, Circuits tancats de càmeres de seguretat.</p>
        </div>
        <div>
          <h3 className="font-medium">2002: Freelance</h3>
          <p>Disseny i desenvolupament web: to2djs.net - HTML, FLASH</p>
        </div>
        <div>
          <h3 className="font-medium">2001: GGG Grup Gràfics Girona (Dpto. UdG) – Desenvolupament mini CAVE3D</h3>
        </div>
        <div>
          <h3 className="font-medium">2001: Disseny i Desenvolupament web ScratchComando.com - HTML, FLASH</h3>
        </div>
        <div>
          <h3 className="font-medium">1999: Jutjat de 1a Instància i Instrucció número 6 Girona</h3>
        </div>
        <div>
          <h3 className="font-medium">1994-1996: Rank Xerox Barcelona</h3>
          <p>Programador durante 14 meses.</p>
        </div>
      </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Habilitats</h2>
        <p>Metodologia LEAN i DevOps:</p>
        <p>Àmplia experiència en la implementació de metodologies LEAN per a l`coptimització de processos.</p>
        <p>Coneixements sòlids en DevOps, facilitant la integració contínua i el lliurament continu de programari.</p>
        <p>Capacitat per identificar i eliminar desaprofitaments, millorant l`eficiència operativa i reduint costos.</p>
        <p>Capacitat Organitzativa i Resolutiva:</p>
        <p>Habilitat destacada per planificar, coordinar i executar projectes complexos, assegurant el compliment de terminis i objectius.</p>
        <p>Capacitat analítica per resoldre problemes tècnics i operatius de manera eficient.</p>
        <p>Experiència en la gestió d`equips multidisciplinaris i en la presa de decisions estratègiques.</p>
        <p>Habilitats Comercials:</p>
        <p>Forta orientació als resultats amb un enfocament en la satisfacció del client i la creació de valor.</p>
        <p>Habilitat per negociar i tancar acords amb proveïdors i socis comercials.</p>
        <p>Coneixement en anàlisi de mercat i desenvolupament d`estratègies comercials efectives.</p>
        <p>Treball en Equip i Autonomia:</p>
        <p>Capacitat per liderar equips de treball, fomentant un ambient de col·laboració i comunicació efectiva.</p>
        <p>Habilitat per treballar de manera autònoma, gestionant prioritats i complint objectius de forma independent.</p>
        <p>Experiència en la creació d`un ambient de treball positiu i en el desenvolupament del talent de l`equip.</p>
        <p>Tecnologies de SmartCity:</p>
        <p>Coneixement en la implementació de solucions tecnològiques per a la gestió de ciutats intel·ligents, com IoT, Big Data i sistemes d`informació geogràfica (SIG).</p>
        <p>Innovació i Desenvolupament Tecnològic:</p>
        <p>Capacitat per impulsar la innovació i l`adopció de noves tecnologies en l`àmbit de les SmartCities.</p>
        <p>Experiència en la gestió de projectes de R+D, des de la conceptualització fins a la implementació.</p>
      </div>
      <div className="mt-6">
        <h2 className="text-2xl font-semibold mb-2">Llicències</h2>
        <p>Carnet B1.</p>
      </div>
    </div>
  )
}

